export const FETCH_LEAGUES = 'FETCH_LEAGUES';
export const INVALID_USERNAME = 'INVALID_USERNAME';
export const FETCH_ROSTER = 'FETCH_ROSTER';
export const FETCH_PAYOUT = 'FETCH_PAYOUT';
export const FETCH_MATCHUPPOINTS = 'FETCH_MATCHUPPOINTS';
export const SET_LEAGUE_ID = 'SET_LEAGUE_ID';
export const FETCH_AVATAR = 'FETCH_AVATAR';