// SLEEPER
export const FETCH_LEAGUES = 'FETCH_LEAGUES';
export const INVALID_USERNAME = 'INVALID_USERNAME';
export const FETCH_ROSTER = 'FETCH_ROSTER';
export const FETCH_PAYOUT = 'FETCH_PAYOUT';
export const FETCH_MATCHUPPOINTS = 'FETCH_MATCHUPPOINTS';
export const SET_LEAGUE_ID = 'SET_LEAGUE_ID';
export const FETCH_AVATAR = 'FETCH_AVATAR';
export const SET_WEEK_TO_STATE = 'SET_WEEK_TO_STATE';
export const REFACTORED_MATCHUPS = 'REFACTORED_MATCHUPS';
export const TOP_SCORER = 'TOP_SCORER';
export const CLOSE_ONE = 'CLOSE_ONE';
export const FETCH_GRAPHPPG = 'FETCH_GRAPHPPG';
export const REFACTORED_DATA = 'REFACTORED_DATA';
export const REMOVE_GRAPH_DATA = 'REMOVE_GRAPH_DATA';
export const SET_GRAPH_POINTS_TO_STATE = 'SET_GRAPH_POINTS_TO_STATE';
export const SET_WAIVERS_TO_STATE = 'SET_WAIVERS_TO_STATE';
export const FIRST_PLACE_TO_STATE = 'FIRST_PLACE_TO_STATE';
export const LAST_PLACE_TO_STATE = 'LAST_PLACE_TO_STATE';
export const SET_RECAP_TO_STATE = 'SET_RECAP_TO_STATE';


// ESPN
export const FETCH_ESPN = 'FETCH_ESPN';